name: EOL Check

on: [pull_request]

jobs:
  dos2unix:
    runs-on: ubuntu-latest

    steps:
      # Checkout to code
      - name: Check-out to source code
        uses: actions/checkout@v4.1.1

      # Setup dos2unix
      - name: Install dos2unix
        run: sudo apt install dos2unix

      # Replace every CRLF with LF
      - name: Convert line endings to LF
        run: find . -type f -exec dos2unix {} +
