name: Tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout to code
      - name: Checkout to source code
        uses: actions/checkout@v4.1.1

      # Setup Node as latest
      - name: Setup NodeJS environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: latest

      # Setup npm globaly
      - name: Setup NPM
        run: npm i -g npm

      # Get node_modules cached
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3.3.2
        with:
          path: |
            **/node_modules
          key: cache-node-modules

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Test application
      - name: Test application
        env:
          CI: true
        run: npm run test
